// <auto-generated />
using System;
using DotaGuideToGreatness.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotaGuideToGreatness.DAL.Migrations
{
    [DbContext(typeof(DotaDbContext))]
    [Migration("20210730113333_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotaGuideToGreatness.Domain.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DotaGuideToGreatness.Domain.Entities.Item", b =>
                {
                    b.HasOne("DotaGuideToGreatness.Domain.Entities.Item", null)
                        .WithMany("AssambleRequirements")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("DotaGuideToGreatness.Domain.Entities.Item", b =>
                {
                    b.Navigation("AssambleRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
