// <auto-generated />
using DotaGuideToGreatness.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotaGuideToGreatness.DAL.Migrations
{
    [DbContext(typeof(DotaDbContext))]
    partial class DotaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotaGuideToGreatness.Domain.Entities.Hero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AgilityGain")
                        .HasColumnType("float");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<double>("IntelligenceGain")
                        .HasColumnType("float");

                    b.Property<int>("MainAttribute")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<int>("MaxMana")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartingHealth")
                        .HasColumnType("int");

                    b.Property<int>("StartingMana")
                        .HasColumnType("int");

                    b.Property<double>("StrengthGain")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("DotaGuideToGreatness.Domain.Entities.Spell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CoolDown")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HeroId")
                        .HasColumnType("bigint");

                    b.Property<double>("ManaCost")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ultimate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("DotaGuideToGreatness.Domain.Entities.Spell", b =>
                {
                    b.HasOne("DotaGuideToGreatness.Domain.Entities.Hero", "Hero")
                        .WithMany("Spells")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("DotaGuideToGreatness.Domain.Entities.Hero", b =>
                {
                    b.Navigation("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
